GET http://localhost:3001/api/persons HTTP/1.1

###
GET http://localhost:3001/info HTTP/1.1

####
GET http://localhost:3001/api/persons/641ef0304d91027faa1c6e95 HTTP/1.1

###
DELETE http://localhost:3001/api/persons/641ef0304d91027faa1c6e95 HTTP/1.1

###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Abdulbasit Ola",
    "number": "234-838993992"
}

###
PUT http://localhost:3001/api/persons/641ee8d087f2f5e6bfe90b7c
content-type: application/json

{
    "name": "Abdulbasit Ola",
    "number": "234-81838020"
}

###
POST http://localhost:3001/api/persons
content-type: application/json
